var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var bodyParser = require('body-parser');
var routes = require('./controllers/index');
var users1 = require('./controllers/users1');
var flash = require('connect-flash');
var session = require('express-session');
var fs = require("fs");
var jwt    = require('jsonwebtoken'); // used to create, sign, and verify tokens
var config = require('./config/config'); // get our config file
var jwt = require("express-jwt");
var unless = require('express-unless');
var cookieParser = require('cookie-parser');

module.exports.express = express;
module.exports.path = path;
module.exports.favicon = favicon;
module.exports.logger = logger;
module.exports.bodyParser = bodyParser;
module.exports.routes = routes;
module.exports.users1 = users1;
module.exports.flash = flash;
module.exports.session = session;
module.exports.fs = fs;
module.exports.jwt = jwt;
module.exports.unless = unless;
module.exports.cookieParser = cookieParser;
module.exports.flash = flash;
module.exports.config = config;